apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kayvee-go
  description: Logs for human and machine readability
  owner: unknown
spec:
  type: unknown
  lifecycle: production
  owner: unknown
  system: Clever
