required = ["github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/eapache/go-resiliency"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.24.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
