#!/bin/bash

cat > schema_gen.go <<EOF
// AUTOGENERATED: DO NOT EDIT!

package router

var matchersSchema = \`{"\$ref": "#/definitions/matchers", "definitions": $(cat schema_definitions.json)}\`
var metricsSchema = \`{"\$ref": "#/definitions/metricsOutput", "definitions": $(cat schema_definitions.json)}\`
var alertSchema = \`{"\$ref": "#/definitions/alertOutput", "definitions": $(cat schema_definitions.json)}\`
var analyticsSchema = \`{"\$ref": "#/definitions/analyticsOutput", "definitions": $(cat schema_definitions.json)}\`
var notificationSchema = \`{"\$ref": "#/definitions/notificationOutput", "definitions": $(cat schema_definitions.json)}\`
EOF
